ALTER TABLE residents ADD COLUMN IF NOT EXISTS mother_deceased BOOLEAN DEFAULT FALSE;
ALTER TABLE residents ADD COLUMN IF NOT EXISTS father_deceased BOOLEAN DEFAULT FALSE;
ALTER TABLE residents ADD COLUMN IF NOT EXISTS spouse_deceased BOOLEAN DEFAULT FALSE;
